branches:
  only:
    - "master"
    - "1.0"
before_script:
  - "npm install -g jshint@1.1.0"
  - "phantomjs --version"
  - "export PHANTOMJS_EXECUTABLE='phantomjs --local-to-remote-url-access=yes --ignore-ssl-errors=yes'"
script:
  - make test
notifications:
  irc:
    channels:
      - "irc.freenode.org#casperjs"
